// Generated by translator-agent — locale detection, rewrite, and RTL/dir support
// Deploy on Vercel. Reads Accept-Language, rewrites to /{locale}/path.
// https://github.com/roeychasman/translator-agent

import { NextRequest, NextResponse } from "next/server";

const LOCALES = ["zh-CN","zh-TW","ja","ko","vi","th","id","ms","fil","my","hi","bn","ta","te","mr","gu","kn","ml","pa","ur","fa","tr","he","ar","kk","uz","fr","de","es","pt","pt-BR","it","nl","ca","gl","sv","da","no","fi","is","pl","cs","sk","hu","ro","bg","hr","sr","sl","uk","ru","lt","lv","et","el","ga","sw","am","ha","yo","zu","af","km","lo","ne","si","ka","az","mn"] as const;
const DEFAULT_LOCALE = "en";
const RTL_LOCALES = new Set(["ur","fa","he","ar"]);

function getPreferredLocale(request: NextRequest): string {
  const header = request.headers.get("accept-language");
  if (!header) return DEFAULT_LOCALE;

  const preferred = header
    .split(",")
    .map((part) => {
      const [lang, q] = part.trim().split(";q=");
      return { lang: lang.trim().toLowerCase(), q: q ? parseFloat(q) : 1 };
    })
    .sort((a, b) => b.q - a.q);

  for (const { lang } of preferred) {
    const exact = LOCALES.find((l) => l.toLowerCase() === lang);
    if (exact) return exact;

    const prefix = lang.split("-")[0];
    const partial = LOCALES.find((l) => l.toLowerCase().startsWith(prefix));
    if (partial) return partial;
  }

  return DEFAULT_LOCALE;
}

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Skip if already has a locale prefix
  const hasLocale = LOCALES.some(
    (l) => pathname.startsWith(`/${l}/`) || pathname === `/${l}`
  );
  if (hasLocale) return NextResponse.next();

  // Skip static assets and API routes
  if (
    pathname.startsWith("/_next") ||
    pathname.startsWith("/api") ||
    pathname.includes(".")
  ) {
    return NextResponse.next();
  }

  const locale = getPreferredLocale(request);
  const url = request.nextUrl.clone();
  url.pathname = `/${locale}${pathname}`;

  const response = NextResponse.rewrite(url);

  // Set lang and dir headers for downstream use
  response.headers.set("x-locale", locale);
  response.headers.set("x-dir", RTL_LOCALES.has(locale) ? "rtl" : "ltr");

  return response;
}

export const config = {
  matcher: ["/((?!_next|api|favicon.ico).*)"],
};
