const template = (locales: string[], defaultLocale: string) => `// Generated by translator-agent — locale detection + rewrite middleware
// Deploy on Vercel. Reads Accept-Language, rewrites to /{locale}/path.
// https://github.com/roeychasman/translator-agent

import { NextRequest, NextResponse } from "next/server";

const LOCALES = ${JSON.stringify(locales)} as const;
const DEFAULT_LOCALE = "${defaultLocale}";

function getPreferredLocale(request: NextRequest): string {
  const header = request.headers.get("accept-language");
  if (!header) return DEFAULT_LOCALE;

  const preferred = header
    .split(",")
    .map((part) => {
      const [lang, q] = part.trim().split(";q=");
      return { lang: lang.trim().toLowerCase(), q: q ? parseFloat(q) : 1 };
    })
    .sort((a, b) => b.q - a.q);

  for (const { lang } of preferred) {
    // Exact match (e.g. "pt-br" → "pt-BR")
    const exact = LOCALES.find((l) => l.toLowerCase() === lang);
    if (exact) return exact;

    // Prefix match (e.g. "fr" matches "fr", "ja" matches "ja")
    const prefix = lang.split("-")[0];
    const partial = LOCALES.find((l) => l.toLowerCase().startsWith(prefix));
    if (partial) return partial;
  }

  return DEFAULT_LOCALE;
}

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Skip if already has a locale prefix
  const hasLocale = LOCALES.some(
    (l) => pathname.startsWith(\`/\${l}/\`) || pathname === \`/\${l}\`
  );
  if (hasLocale) return NextResponse.next();

  // Skip static assets and API routes
  if (
    pathname.startsWith("/_next") ||
    pathname.startsWith("/api") ||
    pathname.includes(".")
  ) {
    return NextResponse.next();
  }

  const locale = getPreferredLocale(request);
  const url = request.nextUrl.clone();
  url.pathname = \`/\${locale}\${pathname}\`;

  return NextResponse.rewrite(url);
}

export const config = {
  matcher: ["/((?!_next|api|favicon.ico).*)"],
};
`;

export const generateMiddleware = (locales: string[], defaultLocale?: string): string =>
  template(locales, defaultLocale ?? locales[0]!);
