import { isRTL } from "./locale-styles.ts";

const template = (locales: string[], defaultLocale: string, rtlLocales: string[]) => `// Generated by translator-agent — locale detection, rewrite, and RTL/dir support
// Deploy on Vercel. Reads Accept-Language, rewrites to /{locale}/path.
// https://github.com/roeychasman/translator-agent

import { NextRequest, NextResponse } from "next/server";

const LOCALES = ${JSON.stringify(locales)} as const;
const DEFAULT_LOCALE = "${defaultLocale}";
const RTL_LOCALES = new Set(${JSON.stringify(rtlLocales)});

function getPreferredLocale(request: NextRequest): string {
  const header = request.headers.get("accept-language");
  if (!header) return DEFAULT_LOCALE;

  const preferred = header
    .split(",")
    .map((part) => {
      const [lang, q] = part.trim().split(";q=");
      return { lang: lang.trim().toLowerCase(), q: q ? parseFloat(q) : 1 };
    })
    .sort((a, b) => b.q - a.q);

  for (const { lang } of preferred) {
    const exact = LOCALES.find((l) => l.toLowerCase() === lang);
    if (exact) return exact;

    const prefix = lang.split("-")[0];
    const partial = LOCALES.find((l) => l.toLowerCase().startsWith(prefix));
    if (partial) return partial;
  }

  return DEFAULT_LOCALE;
}

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Skip if already has a locale prefix
  const hasLocale = LOCALES.some(
    (l) => pathname.startsWith(\`/\${l}/\`) || pathname === \`/\${l}\`
  );
  if (hasLocale) return NextResponse.next();

  // Skip static assets and API routes
  if (
    pathname.startsWith("/_next") ||
    pathname.startsWith("/api") ||
    pathname.includes(".")
  ) {
    return NextResponse.next();
  }

  const locale = getPreferredLocale(request);
  const url = request.nextUrl.clone();
  url.pathname = \`/\${locale}\${pathname}\`;

  const response = NextResponse.rewrite(url);

  // Set lang and dir headers for downstream use
  response.headers.set("x-locale", locale);
  response.headers.set("x-dir", RTL_LOCALES.has(locale) ? "rtl" : "ltr");

  return response;
}

export const config = {
  matcher: ["/((?!_next|api|favicon.ico).*)"],
};
`;

export const generateMiddleware = (locales: string[], defaultLocale?: string): string => {
  const rtlLocales = locales.filter(isRTL);
  return template(locales, defaultLocale ?? "en", rtlLocales);
};
